### PR TITLE
add bcf_reader::Record.id()

### PR DESCRIPTION
**Pull request by jancrichter**
This PR adds a method `id()` to Record, to easily get the variant ID.

In my use case I am using bcf-reader to convert from BCF to a company-internal format that uses the variant ID as index in the first column. I couldn't find a way to access the id field in the Record struct. 

If you think this is a reasonable addition to the library, I will finalize the example for the method.

Please let me know if there already is a way to get the info that I have overlooked. And also please let me know if there is anything missing to make the PR viable if not.

Best regards,
Jan

### CODE REVIEW

**Review by bguo068 — APPROVED** [review]
@jancrichter, thank you for the PR! This change makes sense since the ID is not accessible through the public API and wasn't necessary for my use cases.

I approve the change for now, however, it would be great if you could enhance the doctest for the id() method.

Currently, the BCF files in the testdata folder have empty ID fields. Please feel free to add some fake site IDs to the testdata/test.bcf file and generate a corresponding testdata/test_id.gz file. This will allow you to update the doctest for the id() method.

If you're unfamiliar with this process, I can update testdata/test.bcf, add testdata/test_id.gz, and update the doctest myself. Please let me know.

**Comment by jancrichter** [comment]
@bguo068 thanks for your comments. I updated the doc test and added `%CHROM\_%POS` as ID in test.bcf, although I left a few records with "." instead, to ensure that case is covered as well.

Maybe have a look at how I handle the case of missing ID in the test, as output from bcf_reader will be an empty string, whereas bcftools outputs the ".".

**Comment by bguo068** [comment]
> @bguo068 thanks for your comments. I updated the doc test and added `%CHROM\_%POS` as ID in test.bcf, although I left a few records with "." instead, to ensure that case is covered as well.
> 
> Maybe have a look at how I handle the case of missing ID in the test, as output from bcf_reader will be an empty string, whereas bcftools outputs the ".".

Looks great to me. I just merged the PR.  Thank you for your contribution!

**Comment by bguo068** [comment]
The added method should be availabe on crate.io now: https://crates.io/crates/bcf_reader/0.2.4

**Comment by jancrichter** [comment]
Awesome, thanks for the quick release!

**Pull request merged**
